[package]
name = "cli_interface"
version = "0.1.0"
edition = "2024"

[dependencies]
log  = "0.4"
env_logger = "0.11"
clap = { version = "4.5", features = ["derive"] }
project_navigator = {path = "../project_navigator"} 
